project:
  type: website

website:
  title: "Perception, Action, and Development Lab"
  
  navbar:
    background: primary
    logo: images/icon-plain.png
    title: false
    search: true
    left:
      - text: "Home"
        file: index.qmd
      - text: "Publications"
        file: Publications.qmd
      - People.qmd
      - Contact.qmd

format:
  html:
    theme: lumen
    css: styles.css
    toc: true

editor: visual

