project:
  type: website
  output-dir: htdocs
  resources: publications

website:
  title: "Perception, Action, and Development Lab"
  google-analytics: "G-QC34BLK3LZ"
  favicon: images/favicon.svg
  page-footer: "Copyright 2024, John Franchak" 
  
  navbar:
    logo: images/icon-plain.png
    title: false
    search: true
    left:
      - text: "Home"
        file: index.qmd
      - News.qmd
      - Publications.qmd
      - text: "Open Science"
        menu:
          - text: "Software Tools"
            file: Tools.qmd
          - text: "Shared Datasets"
            file: Datasets.qmd
          - text: "Data Science Course"
            file: course_materials.qmd
          - text: "Head-Mounted Eye Tracking Tutorial"
            href: https://github.com/ICIS-HMET-Workshop/workshop_materials_2022
      - text: "People"
        menu:
          - text: "Prof. John Franchak"
            file: people/john-franchak.qmd
          - text: "All PADLAB Members"
            file: People.qmd
      - Contact.qmd
    right:
      - icon: github
        href: https://github.com/JohnFranchak/padlab_quarto
      - icon: twitter
        href: https://twitter.com/JohnFranchak
      - icon: envelope
        href: mailto:padlab.UCR@gmail.com

format:
  html:
    theme: lumen
    css: styles.css
    toc: true


