project:
  type: website
  output-dir: htdocs
  resources: publications
  render:
    - "*.qmd"
    - "!Franchak_Research.qmd"
    - "!Franchak_Teaching.qmd"
    - "!Franchak_Service.qmd"
    - "!Franchak_Research_2022.qmd"
    - "!Franchak_Research_2page.qmd"
    - "!people/inactive/*.qmd"
    
website:
  title: "Perception, Action, and Development Lab"
  google-analytics: "G-QC34BLK3LZ"
  favicon: images/favicon.svg
  page-footer: "Copyright 2026, John Franchak" 
  
  navbar:
    logo: images/icon-plain.png
    title: false
    search: true
    left:
      - text: "Home"
        file: index.qmd
      - News.qmd
      - Publications.qmd
      - text: "Open Science"
        menu:
          - text: "Software Tools"
            file: Tools.qmd
          - text: "Shared Datasets"
            file: Datasets.qmd
          - text: "Data Science Course"
            file: course_materials.qmd
          - text: "Head-Mounted Eye Tracking Tutorial"
            href: https://github.com/ICIS-HMET-Workshop/workshop_materials_2022
      - text: "People"
        menu:
          - text: "Prof. John Franchak"
            file: people/john-franchak.qmd
          - text: "All PADLAB Members"
            file: People.qmd
      - Contact.qmd
      - text: "Participate"
        href: https://redcap.ucr.edu/surveys/?s=RPFCEENWTJNRKR34&source_tracking=padlab
    right:
      - icon: github
        href: https://github.com/JohnFranchak/padlab_quarto
      - icon: bluesky
        href: https://bsky.app/profile/johnfranchak.bsky.social
      - icon: instagram
        href: https://www.instagram.com/ucr_padlab/
      - icon: linkedin
        href: https://www.linkedin.com/in/john-franchak-b14b34408/
      - icon: envelope
        href: mailto:padlab.UCR@gmail.com

format:
  html:
    theme: 
      - lumen
      - custom.scss
    toc: true


