project:
  type: website
  output-dir: htdocs
  resources: publications

website:
  title: "Perception, Action, and Development Lab"
  google-analytics: UA-61037683-2
  favicon: images/favicon.svg
  page-footer: "Copyright 2022, John Franchak" 
  
  navbar:
    background: primary
    logo: images/icon-plain.png
    title: false
    search: true
    left:
      - text: "Home"
        file: index.qmd
      - News.qmd
      - Publications.qmd
      - Tools.qmd
      - People.qmd
      - Contact.qmd
    right:
      - icon: github
        href: https://github.com/JohnFranchak/padlab_quarto
      - icon: twitter
        href: https://twitter.com/JohnFranchak
      - icon: envelope
        href: mailto:padlab.UCR@gmail.com

format:
  html:
    theme: lumen
    css: styles.css
    toc: true


