project:
  type: website
  output-dir: htdocs
  resources: publications

website:
  title: "Perception, Action, and Development Lab"
  google-analytics: UA-61037683-2
  
  navbar:
    background: primary
    logo: images/icon-plain.png
    title: false
    search: true
    left:
      - text: "Home"
        file: index.qmd
      - text: "Publications"
        file: Publications.qmd
      - People.qmd
      - Contact.qmd
    right:
      - icon: github
        href: https://github.com/JohnFranchak/padlab_quarto

format:
  html:
    theme: lumen
    css: styles.css
    toc: true

editor: visual

