--- 
execute:
  echo: false
  warning: false
format:
  html:
    toc-location: left
    toc-depth: 4
    email-obfuscation: javascript
  pdf: 
    sansfont: "Helvetica"
    geometry:
      - top=24mm
      - left=24mm
      - bottom=24mm
      - right=24mm
      - heightrounded
    fontenc: T1
    colorlinks: true
    block-headings: false
    include-in-header: 
      text: |
        \usepackage{array,colortbl}
        \arrayrulecolor{white}
        \usepackage{fancyhdr}
        \pagestyle{fancy}
        \fancyhead{}
        \fancyhead[LO,LE]{\textbf{\sffamily John Franchak - Teaching Statement}}
        \fancyhead[RO,RE]{\sffamily \thepage}
        \fancyfoot{}
        \RedeclareSectionCommand[
          beforeskip=0pt,
          afterskip=-1.25ex plus .1ex]{paragraph}
        \RedeclareSectionCommand[
          beforeskip=0pt,
          afterskip=1pt]{subsection}
---

::: {.content-visible when-format="html"}
# John Franchak - Teaching Statement 
{{< fa file-pdf title="Download" >}} [Download Teaching Statement](https://padlab.ucr.edu/Franchak_Teaching.pdf)
:::

\thispagestyle{fancy}

# Classroom Instruction 

As faculty at UC Riverside, I have had the pleasure of teaching both undergraduate courses---including larger lectures and smaller seminars---and doctoral courses. Student evaluations for my courses have been consistently positive and score above the mean for the psychology department (which is above the mean for the campus as a whole). I value and enjoy the privilege of teaching and appreciate the challenge of tinkering with my courses to improve students’ experiences and learning. I am prepared and excited to teach courses in **developmental psychology, research methods, infant development, cognitive development, perception, motor control, data science, and programming skills** (R, Julia, Matlab, Quarto, git) at undergraduate and graduate levels.

Each year at UCR, I have taught the undergraduate research methods course, which involves a lecture with 120-140 students and oversight of 6-7 teaching assistants who run weekly, writing-intensive laboratory sections. Research methods is not a class that most students are excited to take---it is the final lower division course that students must pass to take more specialized courses. Moreover, many students are intimidated by the material. However, it is a course that I relish teaching because I have the opportunity to surprise students by showing them why they *should* care about research methodology---which is important not only for psychology majors but for anyone who needs to evaluate research claims that are encountered in everyday life. After the shift to remote instruction during the COVID-19 pandemic, I sought to make the online course stronger by pursuing a UCR XCITE Remote Course Conversion Grant. I was awarded an $8000 grant to enhance the class: I completed the Online Learning Consortium's Foundation Course Certificate and worked with an instructional designer to make the course more engaging online through social reading technology and interactive virtual labs. 

I have also taught two undergraduate seminars (20-30 students) in more specialized topics, such as "Perceptual-Motor Development". With smaller undergraduate classes, I use a hybrid lecture/seminar approach. I briefly lecture to provide breadth on a topic and then lead a class discussion to get into the details of readings. To improve students' ability to critically read and understand empirical papers, I implemented "group reading presentations" in which students meet in groups of 4-5 to plan and present 5-minute Powerpoint presentations. For the presentations, each student covers one of the sections (e.g., motivation, method, results, implications), but putting together an effective presentation requires students to communicate with each other to figure out how each section corresponds with and supports the others. Although students initially balked at the idea of getting up in front of class 5-6 times per quarter to give oral presentations, by the end of the course it was their favorite feature of the class. Students became more confident at presenting and more competent in analyzing research articles. For example, one student evaluation commented, "His class was out of my comfort zone because we did multiple presentations and I don't like public speaking. But it definitely changed my confidence."

I actively filled curriculum gaps to provide new opportunities for undergraduate students. I developed and gained catalog approval for two undergraduate courses: "Infancy", an upper-division elective (50-70 students) that focuses on perceptual, motor, cognitive, social, and emotional development from birth to 2 years, and "Laboratory in Motor Control", in which students use video coding, kinematic and inertial measurements, and eye tracking to design and conduct their own studies. I have taught the Infancy course four times with strong teaching evaluations, and I am offering the laboratory course for the first time in Spring 2026. 

For graduate courses, I taught the core course in Cognitive Development five times, which all developmental psychology graduate students are required to take (and which students in other areas take for breadth).  I developed and taught two graduate seminars, "Vision in Everyday Behavior" and "Developmental Cascades." I believe that student learning in graduate coursework depends on how much effort they are willing to put into reading and participation. To ensure that students are well-prepared, I avoid open-ended student-led discussions in favor of regimented article presentations and discussion leading. Discussion leaders give timed slideshow presentations about 2-3 articles and then lead discussions afterwards. Besides ensuring that students are better organized, creating presentation slides with the class helps students with later studying for qualifying exams and future teaching preparation. 

I developed a new graduate course ["Principles of Data Science"](https://2025-psyc-259.github.io/course_site/syllabus.html) that provides an advanced tutorial in R programming and covers best practices for data sharing and open science. Weekly programming lessons focus on concepts that improve coding efficiency and maintenance; students work on a project throughout the term to take an existing analysis project and implement newly-learned programming skills to automate and improve the reliability of their analysis workflow. Shared [Github repositories](https://github.com/psych-259-data-science-2022) help students by providing reusable materials when building their own analyses in the future.

# Mentoring 

Mentoring junior researchers is the most rewarding part of my job. Beyond mentorship in my own lab, which I detail below, I have served as a faculty mentor to first year students as part of the UCR Graduate Division's peer mentoring program. This fall, I started and will oversee a new peer mentoring program for first year psychology graduate students. My approach to mentoring is guided by training I completed through the University of Wisconsin, Madison C.I.M.E.R. curriculum. 

Throughout my career, I have been passionate about mentoring undergraduate research. To date, I have advised 133 undergraduate research assistants (about 12-15 per year) in my lab. Students are involved in every aspect of the research process: scheduling participants, running experimental sessions, attending project meetings, coding and analyzing data, and preparing presentations and manuscripts. My lab runs multiple professional development workshops each year for undergraduate research assistants---most of whom are first-generation college students and/or from racial/ethnic groups underrepresented in STEM fields---and many of our graduates go on to pursue graduate and professional degrees. I have advised four undergraduate honors theses; three thesis advisees co-authored articles and the fourth co-authored a symposium talk at an international conference. Sixteen other undergraduate advisees earned UCR grants to fund independent projects, and one student was awarded a prestigious Chancellor’s Research Fellowship to fund his project. Each of those students presented their work via posters at intramural or extramural conferences. With support from my NSF grant, I mentored four paid summer interns through UCR's Research in Science and Engineering Program, with one student co-authoring a manuscript currently under review.

I am currently advising five doctoral students in my laboratory and have had three graduate students earn their PhDs. My goals in graduate mentorship are to 1) support the development of independent, critical thinking, 2) foster students’ ability to learn new methods and technologies outside of classroom education, and 3) help students learn to evaluate themselves professionally (e.g., understanding strengths and weaknesses, time management, organizational skills, self-critiques of writing). To ensure that there is sufficient time to both meet about research and professional development, I schedule weekly project meetings (with all project personnel) and advising meetings (one-on-one) with my students. In total, my undergraduate and graduate advisees at UCR have contributed 33 conference presentations and published 14 journal articles.

