--- 
execute:
  echo: false
  warning: false
format:
  html:
    toc-location: left
    toc-depth: 4
    email-obfuscation: javascript
  pdf: 
    fontfamily: tgpagella
    geometry:
      - top=24mm
      - left=24mm
      - bottom=24mm
      - right=24mm
      - heightrounded
    fontenc: T1
    colorlinks: true
    block-headings: false
    include-in-header: 
      text: |
        \usepackage{array,colortbl}
        \arrayrulecolor{white}
        \usepackage{fancyhdr}
        \pagestyle{fancy}
        \fancyhead{}
        \fancyhead[LO,LE]{\textbf{John Franchak - Research Statement}}
        \fancyhead[RO,RE]{\thepage}
        \fancyfoot{}
        \RedeclareSectionCommand[
          beforeskip=0pt,
          afterskip=-1.25ex plus .1ex]{paragraph}
        \RedeclareSectionCommand[
          beforeskip=0pt,
          afterskip=1pt]{subsection}
---

::: {.content-visible when-format="html"}
# John Franchak - Research Statement 
{{< fa file-pdf title="Download" >}} [Download Research Statement](https://padlab.ucr.edu/Franchak_Research.pdf)
:::

\thispagestyle{fancy}

People obtain information through purposeful interaction with the environment in a process known as **exploration**. Such active exploration is a key construct in theories of perception and development. The overarching goal of my research program is to understand the real-time and developmental processes that underlie how people gather perceptual information—explore—when observing scenes, guiding motor actions, and engaging in social interactions. I have pursued 3 main lines of research in my lab: 1) **The development of visual exploration**, 2) **How motor exploration shapes real-life opportunities for learning**, and 3) **How exploratory behavior calibrates perception of action possibilities**. Furthermore, I have made significant methodological contributions, such as pioneering the first head-mounted eye-tracking method for studying infants’ naturalistic visual exploration, developing a text-message-based survey system for estimating infants' posture and activity in the home, and creating a machine-learning classification system for automatically measuring infants' body position in the home from wearable inertial sensors. I support open science by developing and sharing research software and by contributing shared Databrary and OSF data repositories.

## The development of visual exploration

What influences where people choose to look when visually exploring scenes, and how do those influences change over development? My research considers how scene factors, task constraints, and the motor movements required to control looking behavior influence visual exploration.

#### Bottom-up and top-down influences on attention 

Prior work suggests that the visual appearance of a target (bottom-up influences) captures the eye gaze of young infants, but older infants' gaze is driven more by a target's meaning (top-down influences). Across a series of four papers, I challenged this view based on recordings of infant, child, and adult eye movements while watching video clips (Franchak et al., 2016, *Infancy*; Kadooka & Franchak, 2020, *Dev. Psych.*; Franchak & Kadooka, in press, *Infancy*; Jing et al., in press, *JECP*). Using a wider set of videos and range of ages than in previous studies, we failed to find evidence of a global age-related shift in attention from bottom-up to top-down features. Instead, participants of all ages prioritized which features are most important to attend to from moment to moment, which varied according to the scene. Moreover, we found that media conventions (e.g., centering of faces in the scene) more strongly influence fixations to faces in videos compared with bottom-up saliency in both infants and children. These findings have implications for using social attention as a biomarker for autism and also for designing educational media to better direct children's attention.

#### Exploring with eyes, head, and body 

Beyond screen-based tasks, it is important to consider how looking is a motor action---observers must coordinate movements of their eyes, heads, and bodies to explore in all directions (Franchak, 2020, *Psych. of Learning & Motivation*). How does the motor act of looking shape how observers visually explore, and how do motor influences change over development? In earlier work, I used mobile eye trackers to reveal that infants' and children's body size and position shapes what they see (Franchak & Adolph, 2010, *Vis. Research*; Franchak et al., 2011, *Chi Dev*; Kretch, Franchak, & Adolph, 2014, *Chi Dev*). Notably, a paper in *Developmental Science* described how infants' real-time body position affects social gaze (Franchak et al., 2018): Infants less often see caregivers’ faces while infants are crawling than while they are sitting or upright. We extended this to ask how infants learn to orient their heads to center information in view---a previously unstudied aspect of attention development---and showed that infants can more easily center objects in view when they are in a sitting/upright position compared with when they are crawling (Luo & Franchak, 2020, *PLoS ONE*). I also identified developmental changes in how infants orient their heads to center faces versus objects (Franchak et al., in revision). Older but not younger infants center objects in view at the expense of caregivers’ faces, which facilitates looking at objects for guiding reaching movements (Franchak & Yu, 2015, *Proc. Cog Sci Society*). 

Ongoing projects in my lab investigate how the coordination of eyes and head support visual exploration and how such coordination develops from infancy to adulthood. By pairing inertial sensing (to measure head rotation) with mobile eye tracking, my mentees and I found that adults' search in a large outdoor environment is driven more by modifying head movements compared with eye movements (Franchak et al., 2021, *PLoS ONE*). We have also discovered that the need to engage lower effort (eyes) versus higher effort (head, body) effectors to visually explore shapes adults' real-time information-gathering decisions when visual targets are placed in different locations (Luo & Franchak, invited revision under review, *Collabra: Psychology*).

#### Methodological contributions 

To facilitate this work, I led the development of the first mobile eye tracking methodology to measure visual exploration in freely-moving infants (Franchak et al., 2011, *Chi Dev*). I have co-organized two pre-conference workshops, contributed three tutorial papers (Franchak, 2017, *Cambridge Ency.*; Slone et al., 2018, *JOVE*; Franchak & Yu, 2022, *Advances in Child Devel.*), and collaborated on the development of computer vision analyses (Lee et al., 2014, *IEEE CVPR*) to help other researchers adopt the method. I actively maintain open source [software tools](https://github.com/ICIS-HMET-Workshop) that aid mobile eye tracking analyses. I was recognized as an APS Rising Star and a Visiting Scholar at the McPherson Eye Research Institute in recognition of these contributions.

## Motor exploration shapes real-life opportunities for learning

Infants' opportunities for learning about objects and people in daily life depend on what they see. If the motor system influences visual exploration, what are the potential consequences for development? In a position paper (Franchak, 2020, *Curr. Opin. Psych.*), I hypothesized that differences in the time that infants spend in different body positions---creating different opportunities for seeing faces and objects---may facilitate later development of language and spatial cognition.

#### Measuring daily experiences with EMA

I devised a novel ecological momentary assessment (EMA) method to measure body position in 3-, 6-, 9-, and 12-month-olds infants by notifying caregivers throughout the day via text message to ask about infants’ current position (Franchak, 2019, *Infancy*). Older infants spent more time upright compared with crawling, which we previously showed facilitates infants' view of faces and objects. Moreover, motor development (learning to sit and walk) altered body position rates, which in turn changes infants’ opportunities for learning about faces and objects. At the 2022 International Congress on Infant Studies, we presented findings from a longitudinal EMA study indicating that infants who can walk independently spend twice as much time holding objects while upright compared to infants who could only crawl. Recently, I was granted a **4-year, $250,000 Opportunity Award from the James S. McDonnell Foundation** to collect video EMA samples from caregivers to gather richer data about infants' home experiences. Repeated sampling of "video snippets" will allow us to link the frequency and timing of object experiences to subsequent learning of object labels.

<!-- As an extension of my interest in everyday experience, I am part of a UCR Center for Health Disparities Research Grant to investigate how home experiences contribute to psychopathology and anxiety in Latinx youth. Latinx youth are at disproportionate risk for anxiety. Characterizing the contextual and sociocultural factors that surround the development of anxiety in this population can facilitate preventative measures and interventions aimed at reducing societal inequities in mental health.  -->

#### Detecting infants' motor experiences with inertial sensing

To better characterize infants' everyday motor experiences, my mentees and I developed and validated a new technique using wearable inertial sensors and machine learning classification to continuously measure infants' body position in the home (Franchak, Scott, & Luo, 2021, *Frontiers in Psychology*). Currently, data collection is ongoing in the 3rd year of a **4-year, $754,957 NSF Developmental Sciences grant** to use the new inertial sensing method combined with EMA and day-long audio recording to test whether changes in body position following the onset of independent sitting and independent walking facilitate vocabulary development. Furthermore, I was awarded an NICHD PLAY Project subaward to collect video observations of everyday infant-caregiver play in the home (including body position and object experiences). These rich, multi-modal datasets will be openly shared on Databrary to create testbeds for constraining theories and generating hypotheses about developmental mechanisms based on home experiences. 

### Exploratory behavior calibrates perception of action possibilities

Possibilities for action depend on the fit between the body and the environment. For example, whether it is possible to walk under a tree branch without hitting the head depends on body height relative to the height of the branch. Perceiving possibilities for action is a challenge because bodies change in size, requiring *recalibration* of perception. My studies reveal that successful recalibration to changes in body size depends on whether people explore in ways that generate information about how action possibilities have changed.

#### Real-time learning from exploratory practice 

Prior work suggested that exploratory practice is not required for recalibration in most tasks (e.g., navigating under barriers or on steps of different heights); general movement experience is sufficient. My work as a graduate student hinted that in another task---squeezing through doorways---exploratory practice does facilitate accurate perception of action possibilities (Franchak et al., 2010, *Vis Res*; Franchak & Adolph, 2014, *APP*). However, it was unclear whether practicing was required for recalibration because practicing the action (squeezing through doorways) also provides general movement experience while participants walked to the doorway.

I published 5 papers while at UCR to disentangle *why* practice leads to recalibration for some actions but not for others. Does practice simply provide a way to generate movement experience, or is outcome feedback (successfully fitting vs failing to fit) important for recalibration? I found that participants who only received movement experience without outcome feedback (walking around the lab and pressing the backpack against a wall) failed to recalibrate, suggesting that practice recalibrates perception because it provides outcome feedback (Franchak, 2017, *APP*). Two papers showed that the role of outcome feedback is task-dependent: Outcome feedback does not calibrate perception in a fitting (compared to squeezing) version of the task (Franchak, 2020, *QJEP*), and the role of feedback differs for judgments of vertical versus horizontal reaching (Gagnon et al., 2021, *IEEE VR*). To determine whether any other means of exploring (besides practice) would lead to recalibration, my students and I examined how participants spontaneously chose to explore (Labinger et al., 2018, *PLoS ONE*). Despite trying a variety of exploratory methods (touching the doorway, walking around the room, practicing fitting through), only participants who chose to practice made accurate judgments. Finally, prior work shows that general movement experience leads to *gradual* recalibration in the stair-stepping task. An undergraduate honors student and I tested the time course of recalibration in the squeezing task (Franchak & Somoano, 2018, *EBR*), and we discovered that practice *rapidly* recalibrated perception, further supporting the claim that outcome feedback, not general movement experience, recalibrates perception in the doorway squeezing task. 

#### Development of exploration for perceptual-motor recalibration

My earlier work shows that perception of possibilities for action improves through infancy and childhood (Franchak & Adolph, 2012, *Dev Psych*; Ishak et al., 2014, *JECP*). In later work, I showed that the ability to use information from practice to recalibrate improves from 4 to 11 years (Franchak, 2019, *JECP*). Although 11-year-olds show an adult-like ability to perceive their unaltered abilities, they lag behind adults in a recalibration task. An intriguing finding was that younger children made riskier decisions and were thus more likely to attempt fitting through doorways---practicing---compared with older children and adults. My work implies that changes in body size may increase the likelihood of motor errors; children’s deficit in recalibration may contribute to higher rates of accidental injury in childhood. 
