---
title: "Recruiting a Doctoral Student"
description: "Dr. Franchak is accepting applications for 2023-2024"
author: "PADLAB"
date: "10/08/2022"
---

The Perception, Action, and Development Lab is accepting applications for doctoral students for the 2023-2024 academic year. A new graduate student would be encouraged to work in one or more of the lab's main lines of research: 1) how perceptual-motor systems adapt to changes in the body and environment, 2) developmental changes in infants’ everyday visual experiences, and 3) factors that influence infants’ looking behavior. Students would gain training in a variety of methods, such as mobile eye tracking, screen-based eye tracking, inertial movement recording, machine learning, and ecological momentary assessment. Students can apply to work with Dr. Franchak in either the [Developmental](https://psychology.ucr.edu/faculty-research/areas-of-study/#tab-id-3) and [Cognition and Cognitive Neuroscience](https://psychology.ucr.edu/faculty-research/areas-of-study/#tab-id-2).

More about [Psychology at UC Riverside](https://psychology.ucr.edu/): 

* The University of California, Riverside is a world-class research university with a diverse undergraduate student body and a mission to provide routes to educational success for underrepresented and first-generation college students. 

* The graduate program in Psychology at UC Riverside offers competitive graduate funding and student support, as well as specialized programs in Diversity & Inclusion Psychology, Quantitative Psychology, and Health & Well Being. 

* The cost of living in Riverside is affordable relative to other cities in Southern California, and Riverside is located within a 1.5-hour drive from Los Angeles and San Diego. 

* Interested applicants are encouraged to visit the department admissions page for more information: [https://psych.ucr.edu/graduate-study/the-application-and-admission-process/](https://psych.ucr.edu/graduate-study/the-application-and-admission-process/). 

* The deadline for full admission consideration is December 1, 2022. 

If you would like more information, please contact [Dr. Franchak](/people/john-franchak.qmd) directly. 


